// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvxqZXvzsgLU0cj_0KWAE4tP6Os0mCyys',
    appId: '1:811783411246:web:d4c32e31109399968ef1bf',
    messagingSenderId: '811783411246',
    projectId: 'type1sickdays',
    authDomain: 'type1sickdays.firebaseapp.com',
    databaseURL: 'https://type1sickdays-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'type1sickdays.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_KTNeXvIHBeTbn5dfjF9GTKNPU_mPRfY',
    appId: '1:811783411246:android:f5e0987a6a0d8fb88ef1bf',
    messagingSenderId: '811783411246',
    projectId: 'type1sickdays',
    databaseURL: 'https://type1sickdays-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'type1sickdays.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFrB786kmZVXGNryLymyuDwtHIGl69qa4',
    appId: '1:811783411246:ios:13acb9c759001e128ef1bf',
    messagingSenderId: '811783411246',
    projectId: 'type1sickdays',
    databaseURL: 'https://type1sickdays-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'type1sickdays.appspot.com',
    iosBundleId: 'com.example.type1SickDays',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFrB786kmZVXGNryLymyuDwtHIGl69qa4',
    appId: '1:811783411246:ios:13acb9c759001e128ef1bf',
    messagingSenderId: '811783411246',
    projectId: 'type1sickdays',
    databaseURL: 'https://type1sickdays-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'type1sickdays.appspot.com',
    iosBundleId: 'com.example.type1SickDays',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvxqZXvzsgLU0cj_0KWAE4tP6Os0mCyys',
    appId: '1:811783411246:web:879a7569ee6c04068ef1bf',
    messagingSenderId: '811783411246',
    projectId: 'type1sickdays',
    authDomain: 'type1sickdays.firebaseapp.com',
    databaseURL: 'https://type1sickdays-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'type1sickdays.appspot.com',
  );
}
